---
- name: Générer le fichier docker-compose.yml
  template:
    src: odoo.yml.j2
    dest: "/home/{{ ansible_user }}/docker-compose.yml"
    mode: 0655

- name: Lancer le docker compose up -d
  command: docker compose -f /home/{{ ansible_user }}/docker-compose.yml up -d