---
# defaults file for ic-webapp
ansible_python_interpreter: /usr/bin/pip3
ic_webapp_container: ic-webapp
ic_webapp_image: "{{ docker_id }}/ic-webapp:v1.0"
ic_webapp_port: 8000
odoo_url: "http://{{ host_odoo_ip }}:8069"
pgadmin_url: "http://{{ host_pgadmin_ip }}:5050"
ic_webapp_network: ic_network_webapp
host_pgadmin_ip: "10.0.36.5"
host_odoo_ip: "10.0.36.6"
docker_id : azeriock