apiVersion: v1
kind: Service
metadata:
  name: pg-admin
  labels:
    app: pg-admin
    env: prod
  namespace: ic-webapp
spec:
  type: ClusterIP
  selector:
    app: pg-admin
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
