---
- hosts: prod
  become: true
  tasks:
    - name: install python3 and pip
      yum:
        name: "{{ item }}"
        state: present
      loop:
        - yum-utils
        - device-mapper-persistent-data
        - lvm2
        - python3
        - python3-pip
        - python3-setuptools

    - name: Install Python dependencies for Docker
      vars:
        ansible_python_interpreter: /usr/bin/python3
      pip:
        name:
          - requests
          - setuptools
          - docker
        executable: /usr/bin/pip3
