apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: odoo-pvc
  labels:
    app: odoo
    env: prod
  namespace: ic-webapp
spec:
  storageClassName: ebs-gp3-sc
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
