apiVersion: apps/v1
kind: Deployment
metadata:
  name: odoo
  labels:
    app: odoo
    env: prod
  namespace: ic-webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: odoo
  template:
    metadata:
      labels:
        app: odoo
    spec:
      containers:
      - image: odoo
        name: odoo
        envFrom:
        - configMapRef:
            name: odoo-config
        env:
        - name: PGSSLMODE
          value: "require"
        - name: PASSWORD
          valueFrom:
            secretKeyRef:
              name: odoo
              key: PASSWORD
        ports:
        - containerPort: 8069
          name: odoo
        volumeMounts:
        - name: lib-odoo-persistent-storage
          mountPath: /var/lib/odoo
      volumes:
      - name: lib-odoo-persistent-storage
        persistentVolumeClaim:
          claimName: odoo-pvc
