# Nom global du projet
compose_project_name: "odoo_stack"

# Réseau et volume
docker_network_name: "{{ compose_project_name }}_net"
docker_volume_name: "{{ compose_project_name }}_data"

# Service Odoo
odoo_service_name: "odoo"
odoo_container_name: "odoo"
odoo_image: "odoo:17.0"
odoo_port: 8069

# Service base de données
db_service_name: "postgres"
db_container_name: "postgres"
db_image: "postgres:15"
db_name: "postgres"
db_user: "odoo"
db_password: "myodoo"